name: Create Tag

on:
  repository_dispatch:
    types: [ version-changed ]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 确保有适当的权限

      - name: Create new tag
        run: |
          # 配置 Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 获取新版本号
          NEW_VERSION=${{ github.event.client_payload.version }}
          echo "Creating new tag v$NEW_VERSION"
          
          # 创建新标签
          git tag v$NEW_VERSION
          if [[ $? -ne 0 ]]; then
            echo "Failed to create tag v$NEW_VERSION"
            exit 1
          fi
          
          # 推送新标签
          git push origin v$NEW_VERSION
          if [[ $? -ne 0 ]]; then
            echo "Failed to push tag v$NEW_VERSION"
            exit 1
          fi
          
          echo "Successfully created and pushed tag v$NEW_VERSION"
